# Generated by Django 3.1.1 on 2020-12-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartroommodel',
            old_name='file',
            new_name='upload_file',
        ),
    ]
